### ISSUE TITLE
Update Says Success then Fail

### ISSUE THREAD

**Issue by jag3773** [Door43/translationKeyboard#14]
After downloading beta3 I ran an update and it said it was updating keyboard id 71 (I think), but then after that it said that the update failed, I can't remember the wording as it disappeared too quickly.  I'm not sure if it worked or not, maybe this was just a UI bug?

Now, when I click on Update it doesn't do anything, is it refusing to update because I already did recently?  If so we need to provide some sort of feedback to that effect.

**Comment by jag3773** [comment]
Saw the same issue on a second device, update appears to succeed, but there was a failed message mixed in the output, too.

**Comment by bknatterud** [comment]
This should work. But you need to uninstall your app first.
