### ISSUE TITLE
Shift Does not Work in English

### ISSUE THREAD

**Issue by jag3773** [Door43/translationKeyboard#16]
With the English keyboard, I press the shift button and I can see a new set of keys but when I try to use them I actually get the regular key map inserted.

For example, trying to input a ! only yields a 1.

**Comment by jag3773** [comment]
Although I don't know Armenian, it appears that this is also an issue with that keyboard (possibly all keyboards?).

**Comment by bknatterud** [comment]
the shift key seems to work on the English keyboard. What browser were you using?

**Comment by jag3773** [comment]
Same thing in the built in Android browser, translationStudio, and a search box.

Note that long pressing on the key works, but using the shift key does not.

**Comment by bknatterud** [comment]
got it. Sorry, for some reason I was thinking you were talking about tk.unfoldingword.org.

we will fix
