### ISSUE TITLE
Update Keyboard on install

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/translationKeyboard#20]
Trying to install keyboard - when I choose 'Update Keyboards' it fails and I get the attached message.
Status : Error: Invalid update. Please try again.
![2015022405374729](https://cloud.githubusercontent.com/assets/9850185/6347700/ec9193f0-bbe7-11e4-8145-03495edd23c6.png)

**Comment by bknatterud** [comment]
Looking into the issue today. Will let you know by the end of the day what is up.

**Comment by bknatterud** [comment]
this is fixed in a build I am pushing up in a moment
