### ISSUE TITLE
Verify Compression

### ISSUE THREAD

**Issue by jag3773** [Door43/translationKeyboard#22]
Related to https://github.com/Door43/translationStudio2/issues/441.

We need to verify that server and app are compressing data in transit.

**Comment by bknatterud** [comment]
By default the webserver compresses data in gzip when sending data. Should we be using something else?

**Comment by jag3773** [comment]
I need you to verify that the app supports compression and is actually
receiving compressed data.

**Comment by bknatterud** [comment]
The sever supports gzip but is not turned on. I will turn it on tomorrow and we will see if everything still works on the app.

**Comment by bknatterud** [comment]
gzip is turned on at tk.unfoldingword.org now
