### ISSUE TITLE
Import Burmese Keyboards

### ISSUE THREAD

**Issue by jag3773** [Door43/translationKeyboard#7]
This app has Burmese keyboards that work well with translationStudio, can we import them?
https://play.google.com/store/apps/details?id=com.mmswdev.mmkeyboard

**Comment by bknatterud** [comment]
FYI. We have been working on this on and off for the last 2 days. We have it working it working on newer Android devices. However, on older devices we need to use a font. We have it working with the font on older devices too, but the app is crashing quite a bit. So we are trying to debug this. We should have it figured out by Saturday this week.
