### ISSUE TITLE
Keyboard does not fill screen

### ISSUE THREAD

**Issue by jag3773** [Door43/translationKeyboard#8]
See screenshot. Device is galaxy tab 4. Problem is in portrait and landscape.
![screenshot_2014-12-30-12-21-58](https://cloud.githubusercontent.com/assets/107731/5581990/b2c9a1f6-901f-11e4-9a74-2facc1acbdc5.png)

**Comment by bknatterud** [comment]
This issue should be resolved. We are not able to reproduce right now.
