### ISSUE TITLE
App Dies

### ISSUE THREAD

**Issue by jag3773** [Door43/translationKeyboard#9]
On my galaxy s5 the app dies every time I try to input text.
![screenshot_2014-12-30-12-45-00](https://cloud.githubusercontent.com/assets/107731/5582148/0aad4d76-9022-11e4-8bba-988164fb7199.png)

**Comment by bknatterud** [comment]
I will send an updated .apk tonight. You will have to download and test to verify this is fixed.

**Comment by bknatterud** [comment]
Since I have not seen anything else on this issue I'm going to assume it has been resolved.
